### ISSUE TITLE
Have you implemented the League yet? what is the status?

### ISSUE THREAD

**Issue by balloch** [kimbring2/AlphaStar_Implementation#5]

**Comment by kimbring2** [comment]
Hello, Balloch.

Currently, I am implementing the Supervised Learning part. I need to make a replay file for the Simple128 map to check code is correct.

The league part will take more time. 

Thank you

**Comment by balloch** [comment]
I am doing a league-like implementation for a separate research project. I will submit a PR  (if you'd like) in the future

**Comment by kimbring2** [comment]
@balloch Hello, that is good idea. Please share anything about your task freely!
