### ISSUE TITLE
This repository enlightens me.

### ISSUE THREAD

**Issue by liuruoze** [kimbring2/AlphaStar_Implementation#6]
Very good job. Hope to see more of your updates.

**Comment by kimbring2** [comment]
@liuruoze Thank you for your compliment! It seems like you are also working on AlphaStar. My code is not fully working on Supervised Learning. Therefore, I try to find a problem now. I hope you can find some useful information from my repo.

**Comment by liuruoze** [comment]
Of course, I will continue to pay attention to your project. If you have any problems, you can also discuss them with me. Some issues will be very helpful after the discussion!
