### ISSUE TITLE
Map 'mini_games\MoveToBeacon.SC2Map' not found.

### ISSUE THREAD

**Issue by ashaokai123** [kimbring2/AlphaStar_Implementation#7]
run this project,There is a problem：‘Map 'mini_games\MoveToBeacon.SC2Map' not found.’
I'm sorry to bother you, but I don't know why. Hope you can answer .Thanks

**Comment by kimbring2** [comment]
Hello, 

You should download a map file from https://github.com/deepmind/pysc2/tree/master/pysc2/maps/mini_games. After that, copy the map file into '/home/[your account]/StarCraftII/Maps' folder. 

You need to download a Starcraft 2 from https://github.com/Blizzard/s2client-proto#downloads based on your OS.

Thank you,

**Comment by ashaokai123** [comment]
Thank you very much for your reply . I download the file form  https://github.com/deepmind/pysc2/tree/master/pysc2/maps/mini_games. Put the file to Windows: C:/Program Files (x86)/StarCraft II/Maps.
But this problem is still unresolved.
Thanks

**Comment by ashaokai123** [comment]
I'm sorry to bother you again.Really want to know the reason. Thank you.

**Comment by kimbring2** [comment]
@ashaokai123 It seem like you need to make one more folder named 'mini_games' inside the Maps folder.

**Comment by ashaokai123** [comment]
> 
> 
> @ashaokai123 It seem like you need to make one more folder named 'mini_games' inside the Maps folder.

Sent you a gmail. Look forward your reply.

**Comment by ashaokai123** [comment]
@kimbring2  I have some good projects, want to cooperate with you. Very much looking forward to your reply.
