### ISSUE TITLE
Failed on running trajectory_generator.py: Could not find map name

### ISSUE THREAD

**Issue by zyp57783** [kimbring2/AlphaStar_Implementation#8]
I did download replay files from : https://drive.google.com/drive/folders/1lqb__ubLKLfw4Jiig6KsO-D0e_wrnGWk?usp=sharing,
but when I tried to run `python trajectory_generator.py --replay_path [your path]/StarCraftII/Replays/local_Simple64/ --saving_path [your path]/pysc2_dataset/simple64`, I got error messages below and got nothing in the saving_path pysc2_dataset/simple64.

OpenGL initialized!
Listening on: 127.0.0.1:18148
Startup Phase 3 complete. Ready for commands.
ConnectHandler: Request from 127.0.0.1:37386 accepted
ReadyHandler: 127.0.0.1:37386 ready
Could not find map name for file: /tmp/sc-k92ku45y/StarCraft II/TempReplayInfo.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
Using default stable ids, none found at: /home/dev/SC2.4.8.2/StarCraftII/stableid.json
Successfully loaded stable ids: GameData\stableid.json
Could not find map name for file: /tmp/sc-k92ku45y/StarCraft II/TempReplayInfo.SC2Replay
player1_race fail
Could not find map name for file: /tmp/sc-k92ku45y/StarCraft II/TempReplayInfo.SC2Replay
Configuring interface options
Configure: raw interface enabled
Configure: feature layer interface enabled
Configure: score interface enabled
Configure: render interface disabled
Launching next game.
Next launch phase started: 2
Next launch phase started: 3
Next launch phase started: 4
Next launch phase started: 5
Next launch phase started: 6
Next launch phase started: 7
Next launch phase started: 8
Starting replay 'TempStartReplay.SC2Replay'
Game has started.
Could not find map name for file: /tmp/sc-k92ku45y/StarCraft II/TempReplayInfo.SC2Replay
player1_race fail
Could not find map name for file: /tmp/sc-k92ku45y/StarCraft II/TempReplayInfo.SC2Replay

OS version is ubuntu16.04, python version is 3.7.7 and other dependencies are installed according to README.

**Comment by kimbring2** [comment]
@zyp57783 Hello, it seems like that problem is not related with Python. Can you try to run 'python -m pysc2.bin.play --replay <path-to-replay>' command for one of replay file? It should show the rendering GUI.
 
Please tell me the result!

**Comment by zyp57783** [comment]
Thanks for your replay. The replay function of pysc2 runs normally for me. The message I mentioned above did not influence generating the dump file. 
I found the problem is that hkl.dump command cannot mkdir a directory recursively if the file_path's directory doesn't exist. So I got no dump files yesterday. 
My suggestion is to check existence of the file_path before hkl.dump.

**Comment by kimbring2** [comment]
@zhang-yingping Thank you for advice. I added a code for that checking to trajectory_generator.py. Sorry for late :D
