### ISSUE TITLE
Failed on running trajectory_generator.py: RuntimeError SC2_x64

### ISSUE THREAD

**Issue by mlx3223mlx** [kimbring2/AlphaStar_Implementation#9]
when I tried to run python trajectory_generator.py, I got error messages below and got nothing in the saving_path pysc2_dataset/simple64.

RuntimeError: Trying to run '/home/auto/StarCraftII/Versions/Base71663/SC2_x64', but it isn't executable.

**Comment by kimbring2** [comment]
@mlx3223mlx Hello, can you run the below command?

$ python -m pysc2.bin.agent --map Simple64
$ python -m pysc2.bin.play --replay <path-to-replay>

Please tell me the result after running them.
